"use client";

import { useReadContract } from "wagmi";
import { NEXIS_ORACLE_ABI, NEXIS_ORACLE_ADDRESS } from "@/lib/chainlink";
import { intelligenceReport as mockReport } from "@/lib/mock-data";
import type { IntelligenceReport } from "@/types";

/**
 * Hook to read the AI Intelligence Report from NexisRiskOracle.
 * The report is generated by the CRE Workflow via Chainlink Functions
 * calling an LLM API, then written on-chain.
 *
 * Falls back to mock data when the contract isn't deployed.
 */
export function useAIReport(): {
  data: IntelligenceReport;
  isLive: boolean;
  isLoading: boolean;
} {
  const isConfigured =
    NEXIS_ORACLE_ADDRESS !==
    "0x0000000000000000000000000000000000000000";

  const { data: reportData, isLoading } = useReadContract({
    address: NEXIS_ORACLE_ADDRESS,
    abi: NEXIS_ORACLE_ABI,
    functionName: "getIntelligenceReport",
    query: {
      enabled: isConfigured,
      refetchInterval: 60_000, // Poll every 60s (reports update less frequently)
    },
  });

  if (reportData && isConfigured && reportData.summary.length > 0) {
    return {
      data: {
        summary: reportData.summary,
        primaryDriver: reportData.primaryDriver,
        secondaryDriver: "", // Not stored on-chain (gas optimization)
        riskOutlook7D: reportData.riskOutlook7D,
        generatedAt: new Date(
          Number(reportData.generatedAt) * 1000
        ).toISOString(),
      },
      isLive: true,
      isLoading: false,
    };
  }

  return {
    data: mockReport,
    isLive: false,
    isLoading,
  };
}
